import streamlit as st
import os
import base64
from PIL import Image
import io
import sys
import subprocess

# Setup Page
st.set_page_config(
    page_title="ToonFace Adventure",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Custom CSS
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
    
    .stApp {
        background-color: #0f172a;
        color: white;
    }
    h1 {
        font-family: 'Press Start 2P', cursive;
        color: #fbbf24;
        text-shadow: 2px 2px 0px #b45309;
        text-align: center;
    }
    .stButton button {
        background-color: #2563eb;
        color: white;
        font-family: 'Press Start 2P', cursive;
        border: none;
        border-bottom: 4px solid #1e40af;
        transition: all 0.1s;
    }
    .stButton button:hover {
        background-color: #3b82f6;
        border-bottom: 4px solid #1d4ed8;
    }
    .stButton button:active {
        transform: translateY(2px);
        border-bottom: none;
    }
</style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# Gemini API Setup
# -----------------------------------------------------------------------------
def install_and_import_genai():
    try:
        from google import genai
        from google.genai import types
        return genai, types
    except ImportError:
        st.warning("Google GenAI SDK not found. Installing now...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "google-genai"])
            from google import genai
            from google.genai import types
            st.success("Installation successful! Reloading...")
            st.rerun()
            return genai, types
        except Exception as e:
            st.error(f"Failed to auto-install google-genai: {e}")
            st.error("Please run: pip install google-genai")
            st.stop()

genai, types = install_and_import_genai()

def get_gemini_client():
    api_key = os.environ.get("API_KEY")
    if not api_key:
        st.error("API_KEY not found in environment variables.")
        st.stop()
    return genai.Client(api_key=api_key)

def generate_cartoon_avatar(image_bytes):
    client = get_gemini_client()
    
    prompt = "Transform this face into a 2D pixel art style video game character head. Make it cute, colorful, and suitable for a side-scrolling platformer. Isolate the head on a solid white background."
    
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash-image',
            contents=[
                types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg"),
                prompt
            ]
        )
        
        # Iterate through parts to find the image
        if response.candidates and response.candidates[0].content and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data:
                    return part.inline_data.data # Returns raw bytes
        
        st.error("No image generated by the model.")
        return None

    except Exception as e:
        st.error(f"Error generating cartoon: {e}")
        return None

# -----------------------------------------------------------------------------
# Game Logic (Embedded JS)
# -----------------------------------------------------------------------------
def get_game_html(avatar_base64):
    return f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
        body {{ margin: 0; overflow: hidden; background: #000; font-family: 'Press Start 2P', cursive; }}
        canvas {{ display: block; margin: 0 auto; border: 4px solid #334155; }}
        #ui {{ position: absolute; top: 10px; left: 10px; color: white; font-size: 20px; z-index: 10; }}
        #game-over {{ display: none; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center; color: white; }}
        button {{ padding: 10px 20px; font-family: 'Press Start 2P'; cursor: pointer; background: #2563eb; color: white; border: 4px solid white; }}
        .right-ui {{ position: absolute; top: 10px; right: 10px; color: white; font-size: 20px; z-index: 10; }}
    </style>
</head>
<body>
    <div id="ui">
        SCORE: <span id="scoreVal">0</span><br/>
        LIVES: <span id="livesVal">3</span>
    </div>
    <div class="right-ui">
        WORLD 1-<span id="levelVal">1</span>
    </div>
    <div id="game-over">
        <h1 id="go-title">GAME OVER</h1>
        <button onclick="resetGame()">TRY AGAIN</button>
    </div>
    <canvas id="gameCanvas" width="800" height="600"></canvas>

    <script>
        const canvas = document.getElementById('gameCanvas');
        const ctx = canvas.getContext('2d');
        const scoreEl = document.getElementById('scoreVal');
        const livesEl = document.getElementById('livesVal');
        const levelEl = document.getElementById('levelVal');
        const goScreen = document.getElementById('game-over');
        const goTitle = document.getElementById('go-title');

        // Assets
        const avatarImg = new Image();
        avatarImg.src = "data:image/png;base64,{avatar_base64}";

        // Game Constants
        const GRAVITY = 0.5;
        const JUMP_FORCE = -14;
        const MOVE_SPEED = 5;
        const FRICTION = 0.8;
        const MAX_LEVEL = 3;
        
        // Game State
        let gameState = 'PLAYING'; 
        let score = 0;
        let lives = 3;
        let currentLevel = 1;
        let cameraX = 0;
        
        // Entities
        let player = {{ x: 50, y: 200, width: 40, height: 40, vx: 0, vy: 0, grounded: false, facingRight: true }};
        let platforms = [];
        let coins = [];
        let enemies = [];
        let keys = {{}};
        let finishLineX = 3000;

        // Level Gen
        function initLevel(lvl) {{
            platforms = [];
            coins = [];
            enemies = [];
            
            // Reset player physics
            player.x = 50;
            player.y = 200;
            player.vx = 0;
            player.vy = 0;
            cameraX = 0;
            levelEl.innerText = lvl;

            if (lvl === 1) {{
                finishLineX = 3000;
                // Ground
                for (let i = 0; i < 40; i++) {{
                    if (i !== 5 && i !== 12 && i !== 25) {{
                        platforms.push({{ x: i * 100, y: 500, width: 100, height: 100, type: 'ground' }});
                    }}
                }}
                platforms.push({{ x: 300, y: 350, width: 150, height: 40, type: 'brick' }});
                platforms.push({{ x: 600, y: 250, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 640, y: 250, width: 40, height: 40, type: 'brick' }});
                platforms.push({{ x: 680, y: 250, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 900, y: 350, width: 100, height: 40, type: 'brick' }});
                platforms.push({{ x: 1300, y: 300, width: 200, height: 40, type: 'brick' }});
                platforms.push({{ x: 1800, y: 440, width: 60, height: 60, type: 'pipe' }});
                platforms.push({{ x: 2200, y: 460, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 2240, y: 420, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 2280, y: 380, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 3000, y: 460, width: 40, height: 40, type: 'block' }}); // Flag base

                [320, 360, 600, 1000, 1400].forEach((x, i) => {{
                    coins.push({{ x, y: 200 + (i%2)*50, width: 20, height: 20, collected: false }});
                }});

                enemies.push({{ x: 500, y: 460, width: 30, height: 30, vx: -2, type: 'goomba', dead: false }});
                enemies.push({{ x: 1000, y: 460, width: 30, height: 30, vx: -2, type: 'goomba', dead: false }});
                enemies.push({{ x: 1400, y: 260, width: 30, height: 30, vx: 2, type: 'goomba', dead: false }});
            
            }} else if (lvl === 2) {{
                finishLineX = 3200;
                // Sky Level
                platforms.push({{ x: 0, y: 500, width: 300, height: 100, type: 'ground' }}); // Start
                
                platforms.push({{ x: 400, y: 400, width: 100, height: 40, type: 'brick' }});
                platforms.push({{ x: 600, y: 300, width: 100, height: 40, type: 'brick' }});
                platforms.push({{ x: 850, y: 400, width: 100, height: 40, type: 'brick' }});
                
                platforms.push({{ x: 1100, y: 500, width: 400, height: 40, type: 'ground' }});
                enemies.push({{ x: 1200, y: 460, width: 30, height: 30, vx: -3, type: 'goomba', dead: false }});
                enemies.push({{ x: 1400, y: 460, width: 30, height: 30, vx: 3, type: 'goomba', dead: false }});

                platforms.push({{ x: 1600, y: 350, width: 80, height: 40, type: 'block' }});
                platforms.push({{ x: 1800, y: 250, width: 80, height: 40, type: 'block' }});
                platforms.push({{ x: 2000, y: 350, width: 80, height: 40, type: 'block' }});
                platforms.push({{ x: 1800, y: 550, width: 100, height: 40, type: 'brick' }}); // Trap

                platforms.push({{ x: 2300, y: 450, width: 100, height: 40, type: 'brick' }});
                platforms.push({{ x: 2500, y: 350, width: 100, height: 40, type: 'brick' }});
                platforms.push({{ x: 2700, y: 250, width: 100, height: 40, type: 'brick' }});
                
                platforms.push({{ x: 3000, y: 500, width: 400, height: 100, type: 'ground' }});
                platforms.push({{ x: 3200, y: 460, width: 40, height: 40, type: 'block' }});
                
                coins.push({{ x: 640, y: 250, width: 20, height: 20, collected: false }});
                coins.push({{ x: 1830, y: 200, width: 20, height: 20, collected: false }});
                coins.push({{ x: 2740, y: 200, width: 20, height: 20, collected: false }});
            
            }} else if (lvl === 3) {{
                finishLineX = 3500;
                // The Void
                platforms.push({{ x: 0, y: 500, width: 200, height: 100, type: 'ground' }});
                
                platforms.push({{ x: 300, y: 500, width: 60, height: 40, type: 'block' }});
                platforms.push({{ x: 450, y: 450, width: 60, height: 40, type: 'block' }});
                platforms.push({{ x: 600, y: 400, width: 60, height: 40, type: 'block' }});
                platforms.push({{ x: 750, y: 350, width: 60, height: 40, type: 'block' }});

                platforms.push({{ x: 950, y: 200, width: 40, height: 300, type: 'pipe' }}); 
                platforms.push({{ x: 880, y: 450, width: 60, height: 40, type: 'brick' }});

                platforms.push({{ x: 1100, y: 500, width: 500, height: 40, type: 'ground' }});
                enemies.push({{ x: 1200, y: 460, width: 30, height: 30, vx: -4, type: 'goomba', dead: false }});
                enemies.push({{ x: 1400, y: 460, width: 30, height: 30, vx: 4, type: 'goomba', dead: false }});
                platforms.push({{ x: 1250, y: 380, width: 100, height: 40, type: 'brick' }});

                platforms.push({{ x: 1700, y: 400, width: 80, height: 40, type: 'brick' }});
                platforms.push({{ x: 1900, y: 300, width: 80, height: 40, type: 'brick' }});
                
                platforms.push({{ x: 2200, y: 550, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 2350, y: 500, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 2500, y: 450, width: 40, height: 40, type: 'block' }});
                platforms.push({{ x: 2650, y: 400, width: 40, height: 40, type: 'block' }});
                
                platforms.push({{ x: 2900, y: 500, width: 600, height: 100, type: 'ground' }});
                platforms.push({{ x: 3500, y: 460, width: 40, height: 40, type: 'block' }});

                coins.push({{ x: 765, y: 300, width: 20, height: 20, collected: false }});
                coins.push({{ x: 1300, y: 330, width: 20, height: 20, collected: false }});
                coins.push({{ x: 2510, y: 400, width: 20, height: 20, collected: false }});
            }}
        }}

        function resetGame() {{
            gameState = 'PLAYING';
            score = 0;
            lives = 3;
            currentLevel = 1;
            initLevel(1);
            goScreen.style.display = 'none';
            scoreEl.innerText = score;
            livesEl.innerText = lives;
            loop();
        }}

        function resetPlayer() {{
            player.x = 50;
            player.y = 200;
            player.vx = 0;
            player.vy = 0;
            cameraX = 0;
        }}

        // Inputs
        window.addEventListener('keydown', e => keys[e.code] = true);
        window.addEventListener('keyup', e => keys[e.code] = false);

        function checkOverlap(a, b) {{
            return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;
        }}

        function colCheck(shapeA, shapeB) {{
            let vX = (shapeA.x + (shapeA.width / 2)) - (shapeB.x + (shapeB.width / 2));
            let vY = (shapeA.y + (shapeA.height / 2)) - (shapeB.y + (shapeB.height / 2));
            let hWidths = (shapeA.width / 2) + (shapeB.width / 2);
            let hHeights = (shapeA.height / 2) + (shapeB.height / 2);
            let colDir = null;

            if (Math.abs(vX) < hWidths && Math.abs(vY) < hHeights) {{
                let oX = hWidths - Math.abs(vX);
                let oY = hHeights - Math.abs(vY);
                if (oX >= oY) {{
                    if (vY > 0) {{ colDir = "t"; shapeA.y += oY; }}
                    else {{ colDir = "b"; shapeA.y -= oY; }}
                }} else {{
                    if (vX > 0) {{ colDir = "l"; shapeA.x += oX; }}
                    else {{ colDir = "r"; shapeA.x -= oX; }}
                }}
            }}
            return colDir;
        }}

        function update() {{
            if (gameState !== 'PLAYING') return;

            // Move
            if (keys['ArrowRight'] || keys['KeyD']) {{
                if (player.vx < MOVE_SPEED) player.vx++;
                player.facingRight = true;
            }}
            if (keys['ArrowLeft'] || keys['KeyA']) {{
                if (player.vx > -MOVE_SPEED) player.vx--;
                player.facingRight = false;
            }}
            if ((keys['Space'] || keys['ArrowUp'] || keys['KeyW']) && player.grounded) {{
                player.vy = JUMP_FORCE;
                player.grounded = false;
            }}

            player.vx *= FRICTION;
            player.vy += GRAVITY;
            if (player.vy > 12) player.vy = 12; // Terminal velocity
            
            player.x += player.vx;
            player.y += player.vy;
            player.grounded = false;

            // Platforms
            platforms.forEach(p => {{
                let dir = colCheck(player, p);
                if (dir === 'b') {{ player.grounded = true; player.vy = 0; }}
                else if (dir === 't') {{ player.vy *= -0.5; }}
            }});

            // Enemies
            enemies.forEach(e => {{
                if (e.dead) return;
                e.vy = (e.vy || 0) + GRAVITY;
                e.x += e.vx;
                e.y += e.vy;
                
                let eGrounded = false;
                platforms.forEach(p => {{
                    let dir = colCheck(e, p);
                    if (dir === 'b') eGrounded = true;
                    if (dir === 'l' || dir === 'r') e.vx *= -1;
                }});
                if(!eGrounded && e.y > 600) e.y = 500;

                // Collision with player
                if (checkOverlap(player, e)) {{
                    let hitFromAbove = player.vy > 0 && (player.y + player.height - player.vy) < e.y;
                    if (hitFromAbove) {{
                        e.dead = true;
                        player.vy = -8;
                        score += 100;
                    }} else {{
                        lives--;
                        if (lives <= 0) {{
                            gameState = 'GAME_OVER';
                            goTitle.innerText = "GAME OVER";
                            goScreen.style.display = 'block';
                        }} else {{
                            resetPlayer();
                        }}
                    }}
                }}
            }});

            // Coins
            coins.forEach(c => {{
                if (!c.collected && checkOverlap(player, c)) {{
                    c.collected = true;
                    score += 50;
                }}
            }});

            // Level Transition / Win
            if (player.x > finishLineX) {{
                if (currentLevel < MAX_LEVEL) {{
                    currentLevel++;
                    initLevel(currentLevel);
                }} else {{
                    gameState = 'VICTORY';
                    goTitle.innerText = "YOU WIN!";
                    goTitle.style.color = "#4ade80";
                    goScreen.style.display = 'block';
                }}
            }}

            // Fall Death
            if (player.y > 700) {{
                lives--;
                if (lives <= 0) {{
                    gameState = 'GAME_OVER';
                    goTitle.innerText = "GAME OVER";
                    goScreen.style.display = 'block';
                }} else {{
                    resetPlayer();
                }}
            }}

            // Camera
            let targetCamX = player.x - 300;
            cameraX += (targetCamX - cameraX) * 0.1;
            if (cameraX < 0) cameraX = 0;

            scoreEl.innerText = score;
            livesEl.innerText = lives;
        }}

        function draw() {{
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            ctx.save();
            ctx.translate(-cameraX, 0);

            // Sky
            if (currentLevel === 1) ctx.fillStyle = '#6b8cff';
            else if (currentLevel === 2) ctx.fillStyle = '#4a6fa5';
            else ctx.fillStyle = '#2d3748';
            ctx.fillRect(cameraX, 0, canvas.width, canvas.height);

            // Platforms
            platforms.forEach(p => {{
                if (p.type === 'ground') ctx.fillStyle = '#5c9e60';
                else if (p.type === 'brick') ctx.fillStyle = '#b85c3e';
                else if (p.type === 'block') ctx.fillStyle = '#e8b756';
                else if (p.type === 'pipe') ctx.fillStyle = '#28a828';
                ctx.fillRect(p.x, p.y, p.width, p.height);
                ctx.strokeRect(p.x, p.y, p.width, p.height);
            }});

            // Flag
            ctx.fillStyle = '#fff';
            ctx.fillRect(finishLineX + 10, 100, 5, 360);
            ctx.fillStyle = 'red';
            ctx.fillRect(finishLineX + 15, 100, 60, 40);

            // Coins
            ctx.fillStyle = '#ffd700';
            coins.forEach(c => {{
                if (!c.collected) {{
                    ctx.beginPath();
                    ctx.arc(c.x + c.width/2, c.y + c.height/2, c.width/2, 0, Math.PI * 2);
                    ctx.fill();
                }}
            }});

            // Enemies
            enemies.forEach(e => {{
                if (!e.dead) {{
                    ctx.fillStyle = '#8b4513';
                    ctx.fillRect(e.x, e.y, e.width, e.height);
                }}
            }});

            // Draw Player
            // Center X relative to camera
            let cx = player.x + player.width/2;
            let bodyY = player.y + 22;

            // Legs
            ctx.fillStyle = '#2563eb';
            let walkCycle = Math.floor(Date.now() / 100) % 2;
            let isMoving = Math.abs(player.vx) > 0.5;
            let legOffset = isMoving ? (walkCycle ? 3 : -3) : 0;
            
            // Left Leg
            ctx.fillRect(cx - 8 + legOffset, bodyY + 12, 6, 8);
            // Right Leg
            ctx.fillRect(cx + 2 - legOffset, bodyY + 12, 6, 8);

            // Shirt
            ctx.fillStyle = '#dc2626';
            ctx.fillRect(cx - 10, bodyY, 20, 12);

            // Overalls
            ctx.fillStyle = '#2563eb';
            ctx.fillRect(cx - 10, bodyY + 6, 20, 6);
            ctx.fillRect(cx - 8, bodyY, 4, 12);
            ctx.fillRect(cx + 4, bodyY, 4, 12);

            // Buttons
            ctx.fillStyle = '#facc15';
            ctx.fillRect(cx - 7, bodyY + 8, 2, 2);
            ctx.fillRect(cx + 5, bodyY + 8, 2, 2);
            
            // Arms
            ctx.fillStyle = '#dc2626';
            if (isMoving) {{
                // Swing arms
                ctx.fillRect(cx - 14 - legOffset, bodyY + 2, 4, 10);
                ctx.fillRect(cx + 10 + legOffset, bodyY + 2, 4, 10);
            }} else {{
                ctx.fillRect(cx - 14, bodyY + 2, 4, 10);
                ctx.fillRect(cx + 10, bodyY + 2, 4, 10);
            }}

            // Head
            if (avatarImg.complete) {{
                let headSize = 36;
                let headY = player.y - 8;
                ctx.save();
                ctx.beginPath();
                ctx.arc(cx, headY + headSize/2, headSize/2, 0, Math.PI*2);
                ctx.clip();
                if (!player.facingRight) {{
                    ctx.translate(cx + headSize/2, headY);
                    ctx.scale(-1, 1);
                    ctx.drawImage(avatarImg, 0, 0, headSize, headSize);
                }} else {{
                    ctx.drawImage(avatarImg, cx - headSize/2, headY, headSize, headSize);
                }}
                ctx.restore();
            }} else {{
                 // Fallback head
                 ctx.fillStyle = '#fca5a5';
                 ctx.beginPath();
                 ctx.arc(cx, player.y + 10, 16, 0, Math.PI*2);
                 ctx.fill();
            }}

            ctx.restore();
        }}

        function loop() {{
            update();
            draw();
            if (gameState === 'PLAYING') requestAnimationFrame(loop);
        }}

        // Start
        initLevel(1);
        loop();

    </script>
</body>
</html>
    """

# -----------------------------------------------------------------------------
# Main UI
# -----------------------------------------------------------------------------

st.title("🍄 TOONFACE ADVENTURE 🍄")
st.write("### Upload your face -> Get Cartoonized -> Jump!")

col1, col2 = st.columns([1, 2])

with col1:
    uploaded_file = st.file_uploader("Choose an image...", type=['jpg', 'jpeg', 'png'])
    
    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Original', width=200)
        
        if st.button('GENERATE CARTOON & PLAY'):
            with st.spinner('Gemini is painting your sprite...'):
                # Resize to safe limits to prevent 500 errors
                pil_img = image
                max_width = 512
                if pil_img.width > max_width:
                    w_percent = (max_width / float(pil_img.width))
                    h_size = int((float(pil_img.height) * float(w_percent)))
                    pil_img = pil_img.resize((max_width, h_size), Image.Resampling.LANCZOS)
                
                # Convert to bytes
                img_byte_arr = io.BytesIO()
                # Ensure compatibility
                if pil_img.mode in ('RGBA', 'P'):
                    pil_img = pil_img.convert('RGB')
                
                pil_img.save(img_byte_arr, format='JPEG', quality=85)
                img_bytes = img_byte_arr.getvalue()
                
                # Call API
                cartoon_bytes = generate_cartoon_avatar(img_bytes)
                
                if cartoon_bytes:
                    # Convert result to base64 for HTML embedding
                    b64_img = base64.b64encode(cartoon_bytes).decode('utf-8')
                    st.session_state['cartoon_b64'] = b64_img
                    st.success("Character Generated!")

with col2:
    if 'cartoon_b64' in st.session_state:
        st.write("### 🎮 Use Arrow Keys or WASD to Move!")
        
        # Render the game in an iframe
        import streamlit.components.v1 as components
        game_code = get_game_html(st.session_state['cartoon_b64'])
        components.html(game_code, height=650, scrolling=False)
    else:
        st.info("Upload an image and click Generate to start the game.")
        st.markdown("""
        **Instructions:**
        1. Upload a clear photo of a face.
        2. Click 'Generate Cartoon & Play'.
        3. Wait for Gemini 2.5 Flash to create your avatar.
        4. Play the game in the browser window!
        """)