import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

// Helper to resize image to avoid payload limits
const resizeImage = (base64Str: string, maxWidth = 512): Promise<string> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.src = base64Str;
    img.onload = () => {
      let width = img.width;
      let height = img.height;
      
      if (width > maxWidth) {
        height = Math.round((height * maxWidth) / width);
        width = maxWidth;
      }

      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      ctx?.drawImage(img, 0, 0, width, height);
      // Return as JPEG with 0.8 quality to reduce size
      resolve(canvas.toDataURL('image/jpeg', 0.8));
    };
    img.onerror = () => {
        // Fallback to original if loading fails
        resolve(base64Str);
    }
  });
};

export const generateCartoonAvatar = async (base64Image: string): Promise<string> => {
  try {
    const ai = getClient();
    
    // Resize image first to prevent 500 errors due to payload size
    const resizedBase64 = await resizeImage(base64Image);
    
    // Clean base64 string if it contains metadata header
    const cleanBase64 = resizedBase64.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: 'image/jpeg', 
            },
          },
          {
            text: 'Transform this face into a 2D pixel art style video game character head. Make it cute, colorful, and suitable for a side-scrolling platformer. Isolate the head on a solid white background.',
          },
        ],
      },
    });

    // Extract image from response
    // Gemini 2.5 Flash Image returns generated content in the parts
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Error generating cartoon:", error);
    throw error;
  }
};